/* tslint:disable */
/* eslint-disable */
/**
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Risk offsets
 * @export
 * @interface Offsets
 */
export interface Offsets {
    /**
     * 
     * @type {number}
     * @memberof Offsets
     */
    combinedRiskOffset: number;
    /**
     * 
     * @type {number}
     * @memberof Offsets
     */
    fraudRiskOffset: number;
    /**
     * 
     * @type {number}
     * @memberof Offsets
     */
    lendingRiskOffset: number;
    /**
     * 
     * @type {number}
     * @memberof Offsets
     */
    reputationRiskOffset: number;
}
