/* tslint:disable */
/* eslint-disable */
/**
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Offsets } from './offsets';
import { RiskElaboration } from './risk-elaboration';
/**
 * Reason for the risk score
 * @export
 * @interface Reason
 */
export interface Reason {
    /**
     * 
     * @type {string}
     * @memberof Reason
     */
    explanation: string;
    /**
     * 
     * @type {string}
     * @memberof Reason
     */
    label: string;
    /**
     * 
     * @type {Offsets}
     * @memberof Reason
     */
    offsets: Offsets;
    /**
     * 
     * @type {RiskElaboration}
     * @memberof Reason
     */
    riskElaboration: RiskElaboration;
}
