/* tslint:disable */
/* eslint-disable */
/**
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Risk score
 * @export
 * @interface RiskScores
 */
export interface RiskScores {
    /**
     * 
     * @type {number}
     * @memberof RiskScores
     */
    combinedRisk: number;
    /**
     * 
     * @type {number}
     * @memberof RiskScores
     */
    fraudRisk: number;
    /**
     * 
     * @type {number}
     * @memberof RiskScores
     */
    lendingRisk: number;
    /**
     * 
     * @type {number}
     * @memberof RiskScores
     */
    reputationRisk: number;
}
